######################################################################
# Automatically generated by qmake (3.0) Mon Mar 31 14:33:40 2014
######################################################################

TEMPLATE = app
TARGET = implement_new_qtabbar_api
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += main.cpp
